name: 'yq macOS runner installer'
description: 'Install yq onto a GitHub hosted macOS runner and run a command'
inputs:
  cmd:
    description: 'The command which should be run'
    required: true
outputs:
  result:
    description: "The complete result from the yq command being run"
    value: ${{ env.yqresult }}
runs:
  using: composite
  steps:
    - run: ${{ github.action_path }}/install.sh
      shell: bash
branding:
  color: blue
  icon: box