name: 'yq macOS runner installer'
description: 'Install yq onto a GitHub hosted macOS runner'
runs:
  using: composite
  steps:
    - run: ${{ github.action_path }}/install.sh
      shell: bash
branding:
  color: blue
  icon: box